#-----------------------------------------------
# Before running the script be sure that your wd is gipsDAInzynierka
# and that inside it you have data/synthetic_datasets folder
# all .csv files generated by the script will be saved there
#-----------------------------------------------

#-----------------------------------------------
# Sourcing single hyperparameter scenario generation function
#-----------------------------------------------

source("data/generate/all_scenarios_data_functions.R")

#-----------------------------------------------
# Hyperparameters invariant to test/proper
#-----------------------------------------------

dists <- c("exp", "lnorm", "chisq")
perm_type_names <- c("sparse_trans", "dense_trans", "full_cycle")


#-----------------------------------------------
# Test hyperparameters (small quantity so it can run fast)
#-----------------------------------------------

p_test <- c(2,3)
n_classes_test <- c(2,3)
perm_lists_test <- list(list("sparse_trans" = "()", "dense_trans" = "()", "full_cycle" = "(1,2)"),
                          list("sparse_trans" = "(1,2)", "dense_trans" = "(1,3)", "full_cycle" =  "(1,2,3)"))
n_per_class <- 30

#----------------------------------------------
# Test call
#----------------------------------------------


for (i in 1:length(p_test)) {
  p <- p_test[i]

  perm_list <- perm_lists_test[[i]]
  perms_general <- perm_lists_test[[i]]
  names(perms_general) <- c()
  perms_general <- unlist(perms_general)
  for (n in n_classes_test) {
    perms <- perms_general[1:n]
    for (dist in dists) {
      for (perm_type_name in perm_type_names) {
        perm <- perm_list[[perm_type_name]]

        path_prefix <- "data/synthetic_datasets/"
        output_filename_prefix <- paste0(path_prefix,
                                         "synth_",
                                         as.character(p),
                                         "_",
                                         as.character(n),
                                         "_",
                                         dist,
                                         "_",
                                         perm_type_name
        )

        generate_all_scenarios_data(p,
                                    n,
                                    n_per_class,
                                    perm,
                                    perms,
                                    output_filename_prefix,
                                    lambda_dist = dist
        )
      }
    }
  }
}


#-----------------------------------------------
# Proper hyperparameters (target quantity, will run somewhat longer)
#-----------------------------------------------